spring:
  application:
    name: BUKU-SERVICE

  # ================= KAFKA CONFIG =================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      # Group ID digunakan oleh KafkaListener
      group-id: buku-service-group
      auto-offset-reset: earliest
      # NOTE: Deserializer dikonfigurasi di KafkaConsumerConfig.java

  # ================= COMMAND SIDE DATABASE (POSTGRESQL) =================
  datasource:
    url: jdbc:postgresql://localhost:5432/buku_db # Nama DB disesuaikan agar jelas
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dioiwaonen
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ================= QUERY SIDE DATABASE (MONGODB) =================
  data:
    mongodb:
      uri: mongodb://localhost:27017/buku_db # Nama DB disesuaikan agar jelas

  # ================= MAIL CONFIG =================
  mail:
    host: smtp.gmail.com
    port: 587
    username: m.aldioyaspindo@gmail.com
    password: vecl jmds atnu xfup # Sebaiknya simpan ini di environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.aldio: DEBUG # Level log untuk paket aplikasi Anda

server:
  port: 8081